logging:
  level:
    com.example.fileuploadeserver : debug
#    root: debug
#    web: debug
#    sql: debug
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/file_upload
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root



